/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Datos.DAmbiente;
import Entidades.EAmbiente;
import Utils.Exportador;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ENZO
 */
public class ListarAmbientes extends javax.swing.JFrame {

    public DefaultTableModel modelo;
    public String cabecera[] = {"idAmbiente", "Nombre", "Capacidad", "Disponibilidad"};
    
    
    public ListarAmbientes() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        modelo = new DefaultTableModel ( null, cabecera );
        this.LAmbientes.setModel(modelo);
        this.cargarAmbientes();
    }
    
    
    private void cargarAmbientes(){
        DAmbiente pacDao = new DAmbiente();
        ArrayList<EAmbiente> lista;
        
        try{
            lista = pacDao.listarAmbientes();
            for( EAmbiente obj : lista ){
                String disponible;
                if( obj.isDisponibilidad() == true ){
                    disponible = "Disponible";
                }else{
                    disponible = "No Disponible";
                }
                String fila[] = {String.valueOf(obj.getIdAmbiente()),
                                 obj.getNombre(),
                                 String.valueOf(obj.getCapacidad()),
                                 disponible
                                };
                this.modelo.addRow(fila);
            }
        }catch( Exception e ){
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        LAmbientes = new javax.swing.JTable();
        CboxFiltro = new javax.swing.JComboBox<>();
        BtnPDF = new javax.swing.JButton();
        BtnExcel = new javax.swing.JButton();
        BtnRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LAmbientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Capacidad", "Disponibilidad"
            }
        ));
        LAmbientes.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(LAmbientes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 950, 490));

        CboxFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Consultorio", "Sala", "Quirofano" }));
        getContentPane().add(CboxFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, 99, 32));

        BtnPDF.setBackground(new java.awt.Color(68, 1, 30));
        BtnPDF.setFont(new java.awt.Font("Agave Nerd Font", 1, 20)); // NOI18N
        BtnPDF.setForeground(new java.awt.Color(255, 255, 255));
        BtnPDF.setText("Descargar PDF");
        BtnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPDFActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 650, -1, -1));

        BtnExcel.setBackground(new java.awt.Color(68, 1, 30));
        BtnExcel.setFont(new java.awt.Font("Agave Nerd Font", 1, 20)); // NOI18N
        BtnExcel.setForeground(new java.awt.Color(255, 255, 255));
        BtnExcel.setText("Descargar Excel");
        BtnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcelActionPerformed(evt);
            }
        });
        getContentPane().add(BtnExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 650, -1, -1));

        BtnRegresar.setBackground(new java.awt.Color(68, 1, 30));
        BtnRegresar.setFont(new java.awt.Font("Agave Nerd Font", 1, 20)); // NOI18N
        BtnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegresar.setText("Regresar");
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 650, -1, -1));

        jLabel2.setFont(new java.awt.Font("Agave Nerd Font", 1, 20)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/LAmbientes.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnRegresarActionPerformed

    private void BtnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcelActionPerformed
        DAmbiente amb = new DAmbiente();
        List<EAmbiente> ambientes = amb.listarAmbientes();
        Exportador.exportarExcelAmbientes(ambientes, "C:\\Users\\ENZO\\Documents\\ListaAmbientes");
    }//GEN-LAST:event_BtnExcelActionPerformed

    private void BtnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPDFActionPerformed
        DAmbiente amb = new DAmbiente();
        List<EAmbiente> ambientes = amb.listarAmbientes();
        Exportador.exportarPDFAmbientes(ambientes, "C:F:\\PROYECTOS JAVA\\ListaAmbientes.pdf");
    }//GEN-LAST:event_BtnPDFActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarAmbientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarAmbientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarAmbientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarAmbientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarAmbientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnExcel;
    private javax.swing.JButton BtnPDF;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JComboBox<String> CboxFiltro;
    private javax.swing.JTable LAmbientes;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
