/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Datos.DHistorialMedico;
import Entidades.EHistorialMedico;
import Entidades.EPaciente;
import Utils.Exportador;
import java.io.File;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ENZO
 */
public class ListarHistorias extends javax.swing.JFrame {

    private DefaultTableModel modeloTabla;
    private String cabecera[] = {"Codigo", "DNI del Paciente", "Fecha de Creación", "Alergias", "Condiciones Cronicas", "Medicamentos frecuentes", "Numero de atenciones"};
    private DHistorialMedico hisMedDao;
    
    // Formateador para las fechas/horas que vienen de LocalDateTime
    private DateTimeFormatter dateFormatter;
    
    /**
     * Creates new form ListarHistoriales
     */
    public ListarHistorias() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.hisMedDao = new DHistorialMedico(); // Crea una instancia de tu DAO
        
        // Inicializa el modelo de la tabla con la cabecera
        modeloTabla = new DefaultTableModel(null, cabecera) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Hace que las celdas no sean editables
            }
        };
        this.jTable1.setModel(modeloTabla); // Asigna el modelo a tu JTable
        
        this.dateFormatter = DateTimeFormatter.ofPattern("dd-MM-yyyy"); // Define el formato para LocalDate

        cargarHistoriasEnTabla();
    }
    
     // Método para cargar y mostrar los datos en la tabla
    public void cargarHistoriasEnTabla() {
        // Limpiar todas las filas existentes en la tabla antes de cargar nuevas
        modeloTabla.setRowCount(0); 

        // Obtener la lista de historiales médicos de la base de datos a través del DAO
        List<EHistorialMedico> listaHistorias = hisMedDao.listarHistorialesConAtenciones();

        // Verificar si la lista no es nula y llenarla
        if (listaHistorias != null && !listaHistorias.isEmpty()) {
            for (EHistorialMedico historial : listaHistorias) {
                // Preparar los datos para una fila
               String[] fila = new String[cabecera.length]; // Usar la longitud de la cabecera

                // Columna 1: Código del Historial
                fila[0] = historial.getIdHistorial();

                // Datos del Paciente (relacionado 1:1 con HistorialMedico)
                if (historial.getPaciente() != null) {
                    EPaciente paciente = historial.getPaciente();
                    fila[1] = paciente.getDni(); // DNI del Paciente
                } else {
                    fila[1] = "N/A";
                }

                // Columna 3: Fecha de Creación del Historial (usando tu campo "Fecha Cita" como placeholder)
                if (historial.getFechaCreacion() != null) {
                    fila[2] = historial.getFechaCreacion().format(dateFormatter);
                } else {
                    fila[2] = "N/A";
                }

                // Columna 4: Alergias
                fila[3] = historial.getAlergias() != null && !historial.getAlergias().isEmpty() ? historial.getAlergias() : "N/A";

                // Columna 5: Condiciones Crónicas
                fila[4] = historial.getCondicionesCronicas() != null && !historial.getCondicionesCronicas().isEmpty() ? historial.getCondicionesCronicas() : "N/A";

                // Columna 6: medicamentos frecuentes
                fila[5] = historial.getMedicamentosFrecuentes() != null && !historial.getMedicamentosFrecuentes().isEmpty() ? historial.getCondicionesCronicas() : "N/A";
                
                // Aquí mostramos la cantidad de atenciones asociadas a este historial
                int atencionesTotal = historial.getAtenciones().size();
                fila[6] = "" + atencionesTotal; // Muestra el conteo de atenciones

                // Añadir la fila al modelo de la tabla
                this.modeloTabla.addRow(fila);
            }
        } else {
            System.out.println("La lista de historiales médicos obtenida de la base de datos es nula o vacía.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtnCerrar = new javax.swing.JButton();
        BtnDescXls = new javax.swing.JButton();
        BtnDescPdf = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "DNI Paciente", "Fecha Creación", "Alergias", "Condiciones Crónicas", "Medicamentos Frecuentes"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 970, 510));

        BtnCerrar.setBackground(new java.awt.Color(68, 1, 30));
        BtnCerrar.setFont(new java.awt.Font("Agave Nerd Font", 1, 20)); // NOI18N
        BtnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCerrar.setText("Regresar");
        BtnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 650, -1, -1));

        BtnDescXls.setBackground(new java.awt.Color(68, 1, 30));
        BtnDescXls.setFont(new java.awt.Font("Agave Nerd Font", 1, 20)); // NOI18N
        BtnDescXls.setForeground(new java.awt.Color(255, 255, 255));
        BtnDescXls.setText("Descargar Excel");
        BtnDescXls.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnDescXls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDescXlsActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDescXls, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 650, -1, -1));

        BtnDescPdf.setBackground(new java.awt.Color(68, 1, 30));
        BtnDescPdf.setFont(new java.awt.Font("Agave Nerd Font", 1, 20)); // NOI18N
        BtnDescPdf.setForeground(new java.awt.Color(255, 255, 255));
        BtnDescPdf.setText("Descargar PDF");
        BtnDescPdf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnDescPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDescPdfActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDescPdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 650, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/ListaHistorial.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnCerrarActionPerformed

    private void BtnDescXlsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDescXlsActionPerformed
        try{
        DHistorialMedico Dhis = new DHistorialMedico();
        List<EHistorialMedico> Historial = Dhis.listarHistorialesConAtenciones();
        
        // Crear el JFileChooser
        JFileChooser fileChooser = new JFileChooser();
        
        // Configurar filtros para archivos Excel
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos Excel (*.xlsx)", "xlsx");
        fileChooser.setFileFilter(filter);
        
        // Establecer nombre por defecto
        fileChooser.setSelectedFile(new File("ListaHistorial.xlsx"));
        
        // Establecer directorio inicial (opcional)
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        
        // Mostrar el diálogo para guardar
        int result = fileChooser.showSaveDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String filePath = selectedFile.getAbsolutePath();
            
            // Asegurar que tenga extensión .xlsx
            if (!filePath.toLowerCase().endsWith(".xlsx")) {
                filePath += ".xlsx";
            }
            
            // Exportar el Excel
            Exportador.exportarExcelHistorial(Historial, filePath);
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error al exportar Excel: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnDescXlsActionPerformed

    private void BtnDescPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDescPdfActionPerformed
        DHistorialMedico Dhis = new DHistorialMedico();
        List<EHistorialMedico> Historial = Dhis.listarHistorialesConAtenciones();
        
        JFileChooser elegirRuta = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos PDF (*.pdf)", "pdf");
        elegirRuta.setFileFilter(filter);
        
        // Establecer nombre por defecto
        elegirRuta.setSelectedFile(new File("ListaHistorial.pdf"));
        
        // Establecer directorio inicial (opcional)
        elegirRuta.setCurrentDirectory(new File(System.getProperty("user.home")));
        
        // Mostrar el diálogo para guardar
        int result = elegirRuta.showSaveDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = elegirRuta.getSelectedFile();
            String filePath = selectedFile.getAbsolutePath();
            
            // Asegurar que tenga extensión .pdf
            if (!filePath.toLowerCase().endsWith(".pdf")) {
                filePath += ".pdf";
            }
            
            // Exportar el PDF
            Exportador.HistorialExportarPDF(Historial, filePath);
        }
    }//GEN-LAST:event_BtnDescPdfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarHistorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarHistorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarHistorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarHistorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarHistorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCerrar;
    private javax.swing.JButton BtnDescPdf;
    private javax.swing.JButton BtnDescXls;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
