/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Datos.DCita;
import Entidades.ECita;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ENZO
 */
public class ListarCitas extends javax.swing.JFrame {

    public DefaultTableModel modelo;
    public String cabecera[] = {"idCita", "Fecha","Hora", "Motivo", "Estado", "idPaciente", "idEmpleado", "idAmbiente"};
    
    public ListarCitas() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        modelo = new DefaultTableModel ( null, cabecera );
        this.LCitas.setModel(modelo);
        this.cargarCitas();
    }

    private void cargarCitas(){
        DCita pacDao = new DCita();
        ArrayList<ECita> lista;
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat formato2 = new SimpleDateFormat("HH:mm");
        try{
            lista = pacDao.listarCitas();
            for( ECita obj : lista ){
                String fecha = formato.format(obj.getFecha());
                String hora = formato2.format(obj.getHora());
                String fila[] = {String.valueOf(obj.getIdCita()),
                                fecha,
                                hora,
                                obj.getMotivo(),
                                obj.getEstado(),
                                String.valueOf(obj.getPaciente().getIdPersona()),
                                String.valueOf(obj.getEmpleado().getIdPersona()),
                                String.valueOf(obj.getAmbiente().getIdAmbiente())
                                };
                this.modelo.addRow(fila);
            }
        }catch( Exception e ){
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        LCitas = new javax.swing.JTable();
        BtnDescPdf = new javax.swing.JButton();
        BtnCerrar = new javax.swing.JButton();
        BtnDescXls = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "DNI Paciente", "Nombre Paciente", "Apellido Paciente", "Médico", "Consultorio", "Fecha de la cita", "Hora de la cita", "Motivo de la cita", "Estado"
            }
        ));
        LCitas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(LCitas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 960, 510));

        BtnDescPdf.setBackground(new java.awt.Color(68, 1, 30));
        BtnDescPdf.setFont(new java.awt.Font("Agave Nerd Font", 1, 20)); // NOI18N
        BtnDescPdf.setForeground(new java.awt.Color(255, 255, 255));
        BtnDescPdf.setText("Descargar PDF");
        BtnDescPdf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnDescPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDescPdfActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDescPdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 650, -1, -1));

        BtnCerrar.setBackground(new java.awt.Color(68, 1, 30));
        BtnCerrar.setFont(new java.awt.Font("Agave Nerd Font", 1, 20)); // NOI18N
        BtnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCerrar.setText("Regresar");
        BtnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 650, -1, -1));

        BtnDescXls.setBackground(new java.awt.Color(68, 1, 30));
        BtnDescXls.setFont(new java.awt.Font("Agave Nerd Font", 1, 20)); // NOI18N
        BtnDescXls.setForeground(new java.awt.Color(255, 255, 255));
        BtnDescXls.setText("Descargar Excel");
        BtnDescXls.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnDescXls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDescXlsActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDescXls, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 650, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/ListaCitas.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnDescPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDescPdfActionPerformed

    }//GEN-LAST:event_BtnDescPdfActionPerformed

    private void BtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnCerrarActionPerformed

    private void BtnDescXlsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDescXlsActionPerformed

    }//GEN-LAST:event_BtnDescXlsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarCitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCerrar;
    private javax.swing.JButton BtnDescPdf;
    private javax.swing.JButton BtnDescXls;
    private javax.swing.JTable LCitas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
