/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Datos.DPaciente;
import Entidades.EPaciente;
import Entidades.Rol;
import Utils.Exportador;
import java.awt.event.ActionEvent;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

public class ListarPacientes extends javax.swing.JFrame {

    public DefaultTableModel modelo;
    private DPaciente pacDao = new DPaciente();
    public String cabecera[] = {"idPaciente", "DNI", "Tipo de Sangre", "Nombre", "Apellidos", "Rol", "Telefono", "Correo"};
    
    public ListarPacientes() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        modelo = new DefaultTableModel ( null, cabecera );
        this.CboxRolFiltro.addActionListener((ActionEvent e) -> {
            String rolSeleccionado = (String) CboxRolFiltro.getSelectedItem();
            actualizarTabla(rolSeleccionado); // Llama al método para actualizar la tabla
        });
        this.LPacientes.setModel(modelo);
        this.actualizarTabla("Todos");
        this.cargarRoles();
    }
    
    private void cargarRoles() {
        this.CboxRolFiltro.removeAllItems();
        this.CboxRolFiltro.addItem("Todos");
        // Recorrer el enum Rol para añadir las opciones
        for (Rol rol : Rol.values()) {
            if ( !rol.getDbValue().equalsIgnoreCase("Medico") && !rol.getDbValue().equalsIgnoreCase("Enfermero") && !rol.getDbValue().equalsIgnoreCase("Seguridad") && !rol.getDbValue().equalsIgnoreCase("Limpieza")) { 
                this.CboxRolFiltro.addItem(rol.getDbValue());
            }
        }
    }  

    private void actualizarTabla(String rol){
        
        pacDao = new DPaciente();
        modelo = new DefaultTableModel ( null, cabecera );
        this.LPacientes.setModel(modelo);

        List<EPaciente> pacientes;

        if ("Todos".equals(rol)) {
            pacientes = pacDao.listarTodosLosPacientes(rol);
        } else {
            // Convertir el String del ComboBox a un enum Rol
            Rol filtroRol = null;
            try {
                filtroRol = Rol.fromDbValue(rol);
            } catch (IllegalArgumentException e) {
                System.out.println("Error: Rol seleccionado en ComboBox no válido: " + rol);
                return; 
            }
            pacientes = pacDao.listarTodosLosPacientes(filtroRol.getDbValue());
        }

        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy HH:mm");
        // Llenar la tabla con los nuevos datos
        if (pacientes != null) {
            for( EPaciente obj : pacientes ){
                String fila[] = {obj.getIdPersona(),
                                 obj.getDni(),
                                 obj.getTipoSangre().getDbValue(),
                                 obj.getNombre(),
                                 obj.getApellidoPaterno() + " " + obj.getApellidoMaterno(),
                                 obj.getRol().getDbValue(),
                                 obj.getTelefono(),
                                 obj.getCorreo()
                                };
                this.modelo.addRow(fila);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        LPacientes = new javax.swing.JTable();
        CboxRolFiltro = new javax.swing.JComboBox<>();
        BtnDescPdf = new javax.swing.JButton();
        BtnDescXls = new javax.swing.JButton();
        BtnCerrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Apellido Paterno", "Apellido Materno", "Nombres", "DNI", "Historia Clinica"
            }
        ));
        jScrollPane1.setViewportView(LPacientes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 96, 970, 500));

        CboxRolFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(CboxRolFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(799, 18, 108, -1));

        BtnDescPdf.setBackground(new java.awt.Color(68, 1, 30));
        BtnDescPdf.setFont(new java.awt.Font("Agave Nerd Font", 1, 20)); // NOI18N
        BtnDescPdf.setForeground(new java.awt.Color(255, 255, 255));
        BtnDescPdf.setText("Descargar PDF");
        BtnDescPdf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnDescPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDescPdfActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDescPdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 650, -1, -1));

        BtnDescXls.setBackground(new java.awt.Color(68, 1, 30));
        BtnDescXls.setFont(new java.awt.Font("Agave Nerd Font", 1, 20)); // NOI18N
        BtnDescXls.setForeground(new java.awt.Color(255, 255, 255));
        BtnDescXls.setText("Descargar Excel");
        BtnDescXls.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnDescXls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDescXlsActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDescXls, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 650, -1, -1));

        BtnCerrar.setBackground(new java.awt.Color(68, 1, 30));
        BtnCerrar.setFont(new java.awt.Font("Agave Nerd Font", 1, 20)); // NOI18N
        BtnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCerrar.setText("Regresar");
        BtnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 650, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/ListaPaciente.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void BtnDescPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDescPdfActionPerformed
        DPaciente pacDao = new DPaciente();
        List<EPaciente> pacientes = pacDao.listarTodosLosPacientes(this.CboxRolFiltro.getSelectedItem().toString());
        
        JFileChooser elegirRuta = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos PDF (*.pdf)", "pdf");
        elegirRuta.setFileFilter(filter);
        
        // Establecer nombre por defecto
        elegirRuta.setSelectedFile(new File("ListaPacientes.pdf"));
        
        // Establecer directorio inicial (opcional)
        elegirRuta.setCurrentDirectory(new File(System.getProperty("user.home")));
        
        // Mostrar el diálogo para guardar
        int result = elegirRuta.showSaveDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = elegirRuta.getSelectedFile();
            String filePath = selectedFile.getAbsolutePath();
            
            // Asegurar que tenga extensión .pdf
            if (!filePath.toLowerCase().endsWith(".pdf")) {
                filePath += ".pdf";
            }
            
            // Exportar el PDF
            Exportador.pacienteExportarPDF(pacientes, filePath);
        }
    }//GEN-LAST:event_BtnDescPdfActionPerformed

    private void BtnDescXlsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDescXlsActionPerformed
        try{
        DPaciente pacDao = new DPaciente();
        List<EPaciente> pacientes = pacDao.listarTodosLosPacientes(this.CboxRolFiltro.getSelectedItem().toString());
        
        // Crear el JFileChooser
        JFileChooser fileChooser = new JFileChooser();
        
        // Configurar filtros para archivos Excel
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos Excel (*.xlsx)", "xlsx");
        fileChooser.setFileFilter(filter);
        
        // Establecer nombre por defecto
        fileChooser.setSelectedFile(new File("ListaPacientes.xlsx"));
        
        // Establecer directorio inicial (opcional)
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        
        // Mostrar el diálogo para guardar
        int result = fileChooser.showSaveDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String filePath = selectedFile.getAbsolutePath();
            
            // Asegurar que tenga extensión .xlsx
            if (!filePath.toLowerCase().endsWith(".xlsx")) {
                filePath += ".xlsx";
            }
            
            // Exportar el Excel
            Exportador.pacienteExportarExcel(pacientes, filePath);
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error al exportar Excel: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnDescXlsActionPerformed

    private void BtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarPacientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCerrar;
    private javax.swing.JButton BtnDescPdf;
    private javax.swing.JButton BtnDescXls;
    private javax.swing.JComboBox<String> CboxRolFiltro;
    private javax.swing.JTable LPacientes;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
