/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Datos.DAtenciones;
import Entidades.EAtencion;
import Entidades.EPaciente;
import Entidades.E_Empleado;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author guillermo
 */
public class ListarAtenciones extends javax.swing.JFrame {

    /**
     * Creates new form ListarAtenciones
     */
    private DefaultTableModel modeloTabla;
    private String cabecera[] = {"Codigo Cita", "DNI del Paciente", "Nombre del Paciente", "Apellidos del Paciente", "Medico o Enfermero(a)", "Fecha Cita", "Hora Cita", "Diagnostico", "Receta"};
    private DAtenciones atencionDao; // Instancia de tu DAO
    
    // Formateador para las fechas/horas que vienen de LocalDateTime
    private DateTimeFormatter dateTimeFormatter;
    
    public ListarAtenciones() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        atencionDao = new DAtenciones();
        modeloTabla = new DefaultTableModel( null, cabecera );
        this.jTable1.setModel(modeloTabla);
        dateTimeFormatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        dateTimeFormatter = DateTimeFormatter.ofPattern("HH:mm");
        cargarAtencionesEnTabla(); // Carga los datos al iniciar el panel
    }
    
    // Método para cargar y mostrar los datos en la tabla
    public void cargarAtencionesEnTabla() {
        // Limpiar todas las filas existentes en la tabla
        modeloTabla.setRowCount(0); 

        // Obtener la lista de atenciones de la base de datos a través del DAO
        List<EAtencion> listaAtenciones = atencionDao.listarTodasAtenciones();

        // Verificar si la lista no es nula y llenarla
        if (listaAtenciones != null) {
            for (EAtencion atencion : listaAtenciones) {
                // Preparar los datos para una fila
                Object[] rowData = new Object[8]; // 8 columnas

                // Columna 0: Código Cita (de la Atención)
                rowData[0] = (atencion.getCita() != null) ? atencion.getCita().getIdCita() : "N/A";

                // Columnas 1, 2, 3: Datos del Paciente (a través de HistorialMedico)
                if (atencion.getHistorial() != null && atencion.getHistorial().getPaciente() != null) {
                    EPaciente paciente = atencion.getHistorial().getPaciente();
                    rowData[1] = paciente.getDni();
                    rowData[2] = paciente.getNombre();
                    rowData[3] = paciente.getApellidoPaterno() + " " + paciente.getApellidoMaterno();
                } else {
                    rowData[1] = "N/A";
                    rowData[2] = "N/A";
                    rowData[3] = "N/A";
                }

                // Columna 4: Médico o Enfermero (a través de Empleado)
                if (atencion.getEmpleado() != null) {
                    E_Empleado empleado = atencion.getEmpleado();
                    rowData[4] = empleado.getNombre() + " " + empleado.getApellidoPaterno();
                } else {
                    rowData[4] = "N/A";
                }

                // Columna 5: Fecha Cita (de la Cita asociada)
                if (atencion.getCita() != null && atencion.getCita().getFecha() != null) {
                    rowData[5] = atencion.getCita().getFecha();
                } else {
                    rowData[5] = "N/A";
                }
                
                // Columna 6: Hora Cita (de la Cita asociada)
                if (atencion.getCita() != null && atencion.getCita().getHora() != null) {
                    rowData[5] = atencion.getCita().getHora();
                } else {
                    rowData[5] = "N/A";
                }

                // Columna 7: Diagnóstico
                if (atencion.getDiagnostico() != null) {
                    rowData[6] = atencion.getDiagnostico().getDescripcionAdicional();
                } else {
                    rowData[6] = "N/A";
                }

                // Columna 8: Receta
                if (atencion.getReceta() != null) {
                    rowData[7] = atencion.getReceta().getDescripcionAdicional();
                } else {
                    rowData[7] = "N/A";
                }

                // Añadir la fila al modelo de la tabla
                this.modeloTabla.addRow(rowData);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Regresar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo Cita", "Dni Paciente", "Nombre Paciente", "Apellidos Paciente", "Medico o Enfermero", "Fecha Cita", "Diagnóstico", "Receta"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        jButton1.setText("Descargar como Excel");

        jButton2.setText("Descargar como PDF");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Regresar)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_RegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarAtenciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarAtenciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarAtenciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarAtenciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarAtenciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Regresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
