/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Datos.DAmbiente;
import Entidades.EAmbiente;
import Utils.GeneradorCode;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ENZO
 */
public class NewAmbiente extends javax.swing.JFrame {

    private String codeGen;
    
    
    public NewAmbiente() throws SQLException{
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        codeGen = GeneradorCode.CodeGenerador("AMB", null);
        this.codigoAmbiente.setText(codeGen);
    }

    public NewAmbiente(EAmbiente amb) throws SQLException{
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        cargarDatosAmbienteModificar(amb);
    }
    
    public void cargarDatosAmbienteModificar(EAmbiente amb){
        this.codigoAmbiente.setText(amb.getIdAmbiente());
        this.BtnRegister.setText("Actualizar");
        this.TxtNombreAmbi.setText(amb.getNombre());
        this.jSpinnerCapacidad.setValue(amb.getCapacidad());
        this.ChkAmbienteDispo.setText(String.valueOf(amb.isDisponibilidad()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        TxtNombreAmbi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ChkAmbienteDispo = new javax.swing.JCheckBox();
        BtnRegister = new javax.swing.JButton();
        BtnCancel = new javax.swing.JButton();
        jSpinnerCapacidad = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        codigoAmbiente = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(68, 1, 30));
        jLabel2.setText("Nombre del Ambiente:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));
        getContentPane().add(TxtNombreAmbi, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 200, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(68, 1, 30));
        jLabel3.setText("Capacidad de personas:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(68, 1, 30));
        jLabel4.setText("Disponibilidad:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        ChkAmbienteDispo.setSelected(true);
        ChkAmbienteDispo.setText("Disponible");
        getContentPane().add(ChkAmbienteDispo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        BtnRegister.setBackground(new java.awt.Color(68, 1, 30));
        BtnRegister.setFont(new java.awt.Font("Agave Nerd Font", 1, 20)); // NOI18N
        BtnRegister.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegister.setText("Registrar");
        BtnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 130, 30));

        BtnCancel.setBackground(new java.awt.Color(68, 1, 30));
        BtnCancel.setFont(new java.awt.Font("Agave Nerd Font", 1, 20)); // NOI18N
        BtnCancel.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancel.setText("Cancelar");
        BtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 130, 30));
        getContentPane().add(jSpinnerCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 79, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(68, 1, 30));
        jLabel5.setText("Codigo Ambiente:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        codigoAmbiente.setText("codigo");
        getContentPane().add(codigoAmbiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/RAmbientes.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_BtnCancelActionPerformed

    private void BtnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegisterActionPerformed
        //VALIDACIONES PARA LOS DATOS
        if(this.TxtNombreAmbi.getText().length() == 0){
           JOptionPane.showMessageDialog(rootPane, "Ingrese el nombre del Ambiente");
           return; 
        }
        if((int) this.jSpinnerCapacidad.getValue() <= 0){
            JOptionPane.showMessageDialog(rootPane, "La capacidad debe ser mayor a 0");
           return; 
        }
        /*if (!this.ChkAmbienteDispo.isSelected()) {
        JOptionPane.showMessageDialog(rootPane, "El ambiente debe estar disponible al registrarse");
        return;
        }*/
        
        EAmbiente amb = new EAmbiente();
        
        amb.setIdAmbiente(codeGen);
        amb.setNombre(this.TxtNombreAmbi.getText());
        amb.setCapacidad((int)this.jSpinnerCapacidad.getValue());
        //DISPONIBILIDAD AMBIENTE
        amb.setDisponibilidad(this.ChkAmbienteDispo.isSelected());
        
        String tipo[] = {"",""};
        DAmbiente ambDao = new DAmbiente();
        int opc = 1;
        if (this.BtnRegister.getText().equals("Registrar")) {
            opc = confirmacionRegistroModificar(amb, "Registro");
            tipo[0] = "registrar";
            tipo[1] = "registrado";
        }else if (this.BtnRegister.getText().equals("Actualizar")){
            opc = confirmacionRegistroModificar(amb, "Actualizacion");
            tipo[0] = "actualizar";
            tipo[1] = "actualizado";
            amb.setIdAmbiente(this.codigoAmbiente.getText());
        }
        
         if (opc != 0) {
            return;
        }
         
         try {
            if(this.BtnRegister.getText().equals("Registrar")){
                ambDao.registrarAmbiente(amb);
            
            }else if(this.BtnRegister.getText().equals("Actualizar")){
                ambDao.actualizarAmbiente(amb);
            }
        } catch (SQLException ex) {
            Logger.getLogger(NewAmbiente.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "El Ambiente no se pudo registrar, revise que los datos sean correctos.");
            return;
        }
         JOptionPane.showMessageDialog(rootPane, "Ambiente registrado correctamente ");
         try {
            limpiar();
        } catch (SQLException ex) {
            Logger.getLogger(NewPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnRegisterActionPerformed
    
    public int confirmacionRegistroModificar(EAmbiente amb, String confir){
        int opcion = JOptionPane.showConfirmDialog(
            rootPane,
            "<html><b>Datos del Paciente:</b><br>" +
            "Nombre: " + amb.getNombre() + "<br>" +
            "Apellidos: " + amb.getCapacidad(),
            "Verificación del Registro",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.INFORMATION_MESSAGE
        );
        return opcion;
    }
    
    public void limpiar() throws SQLException{
        this.TxtNombreAmbi.setText(null);
        this.jSpinnerCapacidad.setValue(0);
        this.codeGen = GeneradorCode.CodeGenerador("AMB", null);
        this.codigoAmbiente.setText(codeGen);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewAmbiente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewAmbiente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewAmbiente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewAmbiente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new NewAmbiente().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(NewAmbiente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancel;
    private javax.swing.JButton BtnRegister;
    private javax.swing.JCheckBox ChkAmbienteDispo;
    private javax.swing.JTextField TxtNombreAmbi;
    private javax.swing.JLabel codigoAmbiente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSpinner jSpinnerCapacidad;
    // End of variables declaration//GEN-END:variables
}
