
package GUI;

import Datos.Conexion;
import  java.sql.SQLException; 
import java.security.Timestamp;
import java.sql.Connection; 
import java.sql.DriverManager; 
import java.sql.PreparedStatement; 
import java.sql.ResultSet; 
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane; 

/**
 *
 * @author ENZO
 */
public class NewAtencion extends javax.swing.JFrame {

    /**
     * Creates new form NewAtencion
     */
    public NewAtencion() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);        
        cargarCitas(); 
     //   configurarTablaReceta ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        TxtProcedimiento = new javax.swing.JTextField();
        BtnRegister = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        TxtDiagnostico = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        TxtObservacion = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        TxtipoExamen = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        diasTratamiento = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        vecesDiasTratamiento = new javax.swing.JSpinner();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        horasTratamiento = new javax.swing.JSpinner();
        jLabel29 = new javax.swing.JLabel();
        comboMedicamento = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaReceta = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelCodigo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        comboCita = new javax.swing.JComboBox<>();
        labelDni = new javax.swing.JLabel();
        labelFechaCita = new javax.swing.JLabel();
        labelHoraCita = new javax.swing.JLabel();
        labelMotivoCita = new javax.swing.JLabel();
        labelMedico = new javax.swing.JLabel();
        labelAmbiente = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        BtnCancel = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnRegister.setText("Aceptar");
        BtnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegisterActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Registro de Diagnóstico");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel19.setText("Describa el diagnóstico:");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel20.setText("Observaciones:");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel21.setText("Tipo de examen:");

        TxtipoExamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtipoExamenActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel22.setText("Procedimiento:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TxtipoExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TxtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TxtProcedimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(77, 77, 77)
                                    .addComponent(BtnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(TxtDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(jLabel18)))
                .addGap(6, 6, 6))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(TxtDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(TxtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtipoExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtProcedimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addComponent(BtnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Diagnóstico", jPanel2);

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel27.setText("Registro Receta");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel28.setText("Selección de medicamentos:");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setText("Receta:");

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel24.setText("Seleccione el medicamento:");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel26.setText("Indique cuántas veces al día debe administrarse:");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel25.setText("Indique cada cuantas horas debe administrarse el tratamiento :");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel29.setText("Indique los dias del tratamiento:");

        comboMedicamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paracetamol", "Ibuprofeno", "Amoxicilina", "Loratadina", "Omeprazol", "Atorvastatina", "Metformina", "Salbutamol", "Diazepam", "Insulina" }));
        comboMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMedicamentoActionPerformed(evt);
            }
        });

        tablaReceta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaReceta);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(489, 489, 489)
                        .addComponent(jLabel27))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(205, 205, 205)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel29)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addGap(33, 33, 33))
                                    .addComponent(jLabel24))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(diasTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(horasTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vecesDiasTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel27)
                .addGap(62, 62, 62)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel23))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(comboMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(diasTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(horasTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(vecesDiasTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Receta", jPanel3);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setText("Codigo de la cita:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Fecha de la cita: ");

        labelCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCodigo.setText("codigo");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("La hora de la cita: ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Ingrese el motivo de la cita:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText(" DNI del paciente:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Estado:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Nombre del Médico:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText(" Consultorio:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("estado");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel17.setText("Seleccione la cita:");

        comboCita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccione cita", "Control cardíaco", "Examen de piel", "Control pediátrico", "Consulta oftalmológica", "Dolor en rodilla" }));
        comboCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCitaActionPerformed(evt);
            }
        });

        labelDni.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDni.setText("Dni ");

        labelFechaCita.setText("fecha de la cita");

        labelHoraCita.setText("hora de la cita");

        labelMotivoCita.setText("motivo");

        labelMedico.setText("Medico");

        labelAmbiente.setText("ambiente");

        jButton5.setText("Registrar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        BtnCancel.setText("Cancelar");
        BtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(jLabel17)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(labelDni, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboCita, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelFechaCita, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelHoraCita, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelAmbiente, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(labelMotivoCita, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 471, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(BtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(comboCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(labelCodigo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelDni))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelMedico, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelAmbiente, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(labelFechaCita, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labelHoraCita, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(labelMotivoCita, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel7))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jTabbedPane1.addTab("Cita", jPanel1);

        jButton3.setText("Regresar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButton3)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtipoExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtipoExamenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtipoExamenActionPerformed

    private void BtnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnRegisterActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void comboCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCitaActionPerformed
        try{
            if(comboCita.getSelectedItem() != null){
                
                String item = comboCita.getSelectedItem().toString();
                String idCita = item.split("-") [0];
                
                Connection cn = Conexion.getConnect().getConexion(); 
                String sql = "SELECT C.idCita, DATE(C.fechaHora) AS fecha, TIME(C.fechaHora) AS hora, C.motivo, C.estado," 
                        + " P.dni AS dniPaciente, "
                        + "CONCAT (M.nombre, ' ', M.apellidoPaterno, '', M.apellidoMaterno) AS medico, "
                        + "A.nombre AS consultorio "
                        + "FROM CITA C "
                        + "INNER JOIN PACIENTE PA ON C.idPaciente = PA.idPersona "
                        + "INNER JOIN PERSONA P ON PA.idPersona = P.idPersona "
                        + "INNER JOIN EMPLEADO E ON C.idEmpleado = E.idPersona "
                        + "INNER JOIN PERSONA M ON E.idPersona = M.idPersona "
                        + "INNER JOIN AMBIENTE A ON C.idAmbiente = A.idAmbiente "
                        + "WHERE C.IdCita = ?"; 
                PreparedStatement pst = cn.prepareStatement(sql); 
                pst.setString(1, idCita);
                ResultSet rs = pst.executeQuery(); 
                
                if(rs.next()){
                    labelCodigo.setText(rs.getString("idCita"));
                    labelDni.setText(rs.getString("DniPaciente"));
                    labelMedico.setText(rs.getString("Medico"));
                    labelAmbiente.setText(rs.getString ("Consultorio"));
                    labelFechaCita.setText(rs.getString ("Fecha"));
                    labelHoraCita.setText(rs.getString ("Hora"));
                    labelMotivoCita.setText(rs.getString ("Motivo"));
                    jLabel16.setText(rs.getString ("Estado"));

               
                }
                rs.close();
                pst.close();
                cn.close();
                
            }
          } catch (Exception e){
                JOptionPane.showMessageDialog(this, "ERROR al cargar citas: " + e.getMessage());    
        }
    }//GEN-LAST:event_comboCitaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try{
            //obtenemos los datos del formulario 
            String idCita = labelCodigo.getText(); 
            String idPaciente = labelDni.getText(); 
            String idEmpleado = labelMedico.getText();
            String idAmbiente = labelAmbiente.getText();
            String fecha = labelFechaCita.getText().trim(); 
            String hora = labelHoraCita.getText().trim(); 
            String motivo = labelMotivoCita.getText();
            String estado = jLabel16.getText(); 
            
            if(idCita.isEmpty() || fecha.isEmpty() || hora.isEmpty() || idPaciente.isEmpty() || idEmpleado.isEmpty() || idAmbiente.isEmpty() ){
                JOptionPane.showMessageDialog(this, "debe seleccionar una cita validad");
                return; 
            }

           //nuevas mejoraras 
           Connection cn = Conexion.getConnect().getConexion(); 
           String sqlIds ="SELECT idPaciente, idEmpleado, idAmbiente FROM CITA WHERE idCita = ? ";
           PreparedStatement pstIds = cn.prepareStatement(sqlIds);
           pstIds.setString(1, idCita);
           ResultSet rsIds = pstIds.executeQuery(); 
           
           String realIdPaciente = ""; 
           String realIdEmpleado = "";
           String realIdAmbiente = "";
           
           if (rsIds.next()){
               realIdPaciente = rsIds.getString("idPaciente");
               realIdEmpleado = rsIds.getString("idEmpleado");
               realIdAmbiente = rsIds.getString("idAmbiente");
           }
           rsIds.close();
           pstIds.close();
           // hasta aqui 
           
           if(hora.length() == 5 ) {
               hora += ":00";
           }
      //     String fechaHoraSrt = fecha + " "+ hora; 
           
           String fechaHora = fecha+ " " + hora; 
           //fechaHora = Timestamp.valuesOf(fechaHoraStr) ;
         
           //"INSERT INTO CITA(idCita, fechaHora, motivo, estado, idPaciente, idEmpleado, idAmbiente) "
                //    + "VALUES (?,?,?,?,?,?,?)"; VAMIS A VER SI ESE ES EL ERROR
           
          //  Connection cn = Conexion.getConnect().getConexion(); 
            String sql = "UPDATE CITA SET fechaHora=?, motivo=?, estado=?, idPaciente=?, idEmpleado=?, idAmbiente=? WHERE idCita=?";
            PreparedStatement pst = cn.prepareStatement(sql);
            
            pst.setString(1, fechaHora);
            pst.setString(2, motivo);
            pst.setString(3, estado);
            pst.setString(4, realIdPaciente); // se cambio de idPaciente a 
            pst.setString(5, realIdEmpleado); // idEmpleado
            pst.setString(6, realIdAmbiente); // idAmbiente
            pst.setString(7, idCita);
            
            int resultado = pst.executeUpdate(); 
            
            if (resultado > 0 ){
                JOptionPane.showMessageDialog(this, "datos de la cita registrados. ");
            }else{
                JOptionPane.showMessageDialog(this, "error ");
            }
            pst.close();
            cn.close();
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Error al registrar cira " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void BtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnCancelActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Connection cn = null; 
        PreparedStatement pstReceta = null; 
        PreparedStatement pstDetalle = null; 
        PreparedStatement pstVerificarReceta = null;
        PreparedStatement pstActualizarAtencion = null; 
        ResultSet rsReceta = null; 
        ResultSet rsVerificar = null;
        
        try{
            String idMedicamento = comboMedicamento.getSelectedItem().toString(); 
            int dosis = (Integer) diasTratamiento.getValue(); 
            int frecuencia = (Integer) horasTratamiento.getValue();
            int duracionTratamiento= (Integer) vecesDiasTratamiento.getValue();
            String idCita = labelCodigo.getText(); 
            
            if(idCita.isEmpty() || idCita.equals("codigo")){
            JOptionPane.showMessageDialog(this, "debe seleccionar una cita ");
            return; 
            }
            
            if(dosis <= 0 || frecuencia <= 0 || duracionTratamiento <= 0){
            JOptionPane.showMessageDialog(this, "POR FAVOR ingrese valores validos");
            return ;
            }
            
            if(idMedicamento == null || idMedicamento.trim().isEmpty()){
               JOptionPane.showMessageDialog(this, "DEBE Seleccionar un medicamento");
            return ;
            }
            cn = Conexion.getConnect().getConexion(); 
            cn.setAutoCommit(false); // lo agregue recien 
            
            String idReceta = "REC-" + idCita.replace("CIT-", ""); 
             
             /*String sqlBuscarReceta = "SELECT idReceta FROM ATENCION WHERE idCita = ?";
            pstReceta = cn.prepareStatement(sqlBuscarReceta); 
            pstReceta.setString(1, idCita);
           rsReceta = pstReceta.executeQuery(); */
           
             String sqlVerificarReceta = "SELECT idReceta FROM RECETA WHERE idCita = ?";
            pstReceta = cn.prepareStatement(sqlVerificarReceta); 
            pstReceta.setString(1, idReceta);
           rsReceta = pstReceta.executeQuery();
           
           if(!rsReceta.next()){
             //   idReceta = rsReceta.getString("idReceta"); 
               // if (idReceta == null){
                   // idReceta = "REC-" + System.currentTimeMillis(); 
                   rsReceta.close();
                   pstReceta.close();
                    //agregue nuevo
                   String sqlInsertarReceta = "INSERT INTO RECETA (idReceta, descripcionAdicional) VALUES (?, ?)"; 
                 //  pstReceta.close();
                   pstReceta = cn.prepareStatement(sqlInsertarReceta); 
                   pstReceta.setString(1, idReceta);
                   pstReceta.setString(2, "Receta generada para cita: " + idCita); // agregada nueva
                   pstReceta.executeUpdate(); 
                 /*  
                  String  sqlActualizarAtencion = "UPDATE ATENCION SET idReceta = ? WHERE idCita = ?";
                  pstActualizarAtencion = cn.prepareStatement(sqlActualizarAtencion); 
                  pstActualizarAtencion.setString(1, idReceta);
                  pstActualizarAtencion.setString(2, idCita);
                  pstActualizarAtencion.executeUpdate();*/
                   
                   
               // }
           } /*else{
               
               JOptionPane.showMessageDialog(this, "no sé encontro la atencion ");
               return; 
              /* rsReceta.close();
               pstReceta.close();
             
               //idReceta = idCita;
               idReceta = "REC-" + idCita.substring(idCita.lastIndexOf("-") + 1); //agregue nuevo
               
               String sqlVerificar = "SELECT idReceta FROM RECETA WHERE idCita = ?";
               pstVerificarReceta = cn.prepareStatement(sqlVerificar); 
               pstVerificarReceta.setString(1, idReceta);
               rsVerificar = pstVerificarReceta.executeQuery();
               
               if(!rsVerificar.next()){
                   String sqlInsertarReceta = "INSERT INTO receta (idReceta, descripcionAdicional) VALUES (?, ?)"; 
                   pstReceta = cn.prepareStatement(sqlInsertarReceta); 
                   pstReceta.setString(1, idReceta);
                   pstReceta.setString(1, "Receta generada para cita: " + idReceta); // agregada nueva
                   pstReceta.executeUpdate(); 
                   
                   
                   // agregada nueva para actuallizar tabla 
                  String  sqlActualizarAtencion = "UPDATE ATENCION SET idReceta = ? WHERE idCita = ?";
                  pstActualizarAtencion = cn.prepareStatement(sqlActualizarAtencion); 
                  pstActualizarAtencion.setString(1, idReceta);
                  pstActualizarAtencion.setString(2, idCita);
                  pstActualizarAtencion.executeUpdate();
               }*/
           //}*/
            //agregada nuevo para ver si ya existe en la receta 
            
            if(rsReceta != null) rsReceta.close();
            if(pstReceta != null) pstReceta.close();
            
            String sqlVerificarMedicamento = "SELECT idReceta FROM DETALLE_RECETA WHERE idReceta = ? AND idMedicamento = ?"; 
            PreparedStatement pstVerificarMed = cn.prepareStatement(sqlVerificarMedicamento);
            pstVerificarMed.setString(1, idReceta);
            pstVerificarMed.setString(2, idMedicamento);
            ResultSet rsVerificarMed = pstVerificarMed.executeQuery();
            if(rsVerificarMed.next()){
                JOptionPane.showMessageDialog(this, "Este medicamento ya esra en la receta ");
               // rsVerificarMed.close();
               // pstVerificarMed.close();
                return;
            }
            
            rsVerificarMed.close();
            pstVerificarMed.close();
            
           
           
           String sqlDetalle = "INSERT INTO DETALLE_RECETA (idReceta, idMedicamento, dosis, frecuencia, duracionTratamiento) VALUES (?, ?, ?, ?, ?)";
            pstDetalle = cn.prepareStatement(sqlDetalle); 
           
            pstDetalle.setString(1, idReceta);
            pstDetalle.setString(2, idMedicamento);
            pstDetalle.setString(3, dosis + " mg");
            pstDetalle.setString(4, frecuencia + " veces al dia");
            pstDetalle.setString(5, duracionTratamiento + " dias");
            
            int resultado = pstDetalle.executeUpdate(); 
            
            if (resultado > 0 ){
                cn.commit(); // agregue nuevo 
                
                javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tablaReceta.getModel(); 
                Object[] fila = {idMedicamento, dosis + " mg", frecuencia + " veces al dia", duracionTratamiento + " dias"}; 
                model.addRow(fila);
                
                diasTratamiento.setValue(0);
                horasTratamiento.setValue(0);
                vecesDiasTratamiento.setValue(0);
                
                 JOptionPane.showMessageDialog(this, "medicamento agregado ");
            }else{
                cn.rollback();
                 JOptionPane.showMessageDialog(this, "ERROR al agregar");
            }
            //pst.close();
            //cn.close();
            
        }catch(SQLException e){
            try {
                if (cn != null ) cn.rollback();
            }catch (SQLException ex){
                ex.printStackTrace();
            }
           JOptionPane.showMessageDialog(this, "ERROR de base de datos"+ e.getMessage());
           e.printStackTrace();

        }catch(Exception e){
            try{
                if (cn != null) cn.rollback();
            }catch (SQLException ex){
                ex.printStackTrace();
            }
            JOptionPane.showMessageDialog(this, "ERROR al agregar medicamento"+ e.getMessage());
           e.printStackTrace();
        }finally{
            try{
                if (cn != null ) cn.setAutoCommit(true);
                if(rsReceta != null) rsReceta.close();
                if(rsVerificar != null) rsVerificar.close();
                if(pstReceta != null) pstReceta.close();
                if (pstVerificarReceta != null) pstVerificarReceta.close();
                if(pstDetalle != null) pstDetalle.close();
                if(pstActualizarAtencion != null) pstActualizarAtencion.close();
                if(cn != null) cn.close();
            }catch(SQLException e){
                e.printStackTrace();
            }
        }
    }                         
            //Connection cn = Conexion.getConnect().getConexion(); 
           // String sql = "INSERT INTO receta (idReceta, idMedicamento, dosis, frecuencia, duracionTratamiento) VALUES (?, ?, ?, ?, ?)"; 
           // PreparedStatement pst = cn.prepareStatement(sql); 
        /*   String idReceta = ""; 
           String sqlVerifacarReceta = "SELECT idReceta FROM atencion WHERE idCita=?";
           pstReceta = cn.prepareStatement(sqlVerifacarReceta); 
           pstReceta.setString(1, idCita);
           rsReceta = pstReceta.executeQuery(); 
           
           if(rsReceta.next()){
               idReceta = rsReceta.getString("idReceta"); 
               
           }else{
               rsReceta.close();
               pstReceta.close();
               
               String sqlCrearReceta = "INSERT INTO receta (idReceta) VALUES (?)"; 
               pstReceta = cn.prepareStatement(sqlCrearReceta, PreparedStatement.RETURN_GENERATED_KEYS); 
               pstReceta.setString(1, idCita);
               
               int resultadoReceta = pstReceta.executeUpdate();
               if(resultadoReceta > 0){
                   ResultSet rsKey = pstReceta.getGeneratedKeys(); 
                   if(rsKey.next()){
                       idReceta = rsKey.getString(1);
                   }
                   rsKey.close();
               }else{
                   JOptionPane.showMessageDialog(this, "Error al crear receta. ");
                   return; 
               }
           }
           
           String sqlDetalle = "INSERT INTO detalle_receta (idReceta, idMedicamento, dosis, frecuencia, duracionTratamiento) VALUES (?, ?, ?, ?, ?)";
           pstDetalle = cn.prepareStatement(sqlDetalle); 
           
            pstDetalle.setString(1, idReceta);
            pstDetalle.setString(2, idMedicamento);
            pstDetalle.setInt(3, dosis);
            pstDetalle.setInt(4, frecuencia);
            pstDetalle.setInt(5, duracionTratamiento);
            
            int resultado = pstDetalle.executeUpdate(); 
            
            if (resultado > 0 ){
                javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tablaReceta.getModel(); 
                Object[] fila = {idMedicamento, dosis, frecuencia, duracionTratamiento}; 
                model.addRow(fila);
                
                diasTratamiento.setValue(0);
                horasTratamiento.setValue(0);
                vecesDiasTratamiento.setValue(0);
                
                 JOptionPane.showMessageDialog(this, "medicamento agregado ");
            }else{
                 JOptionPane.showMessageDialog(this, "ERROR al agregar");
            }
            //pst.close();
            //cn.close();
            
        }catch(SQLException e){
           JOptionPane.showMessageDialog(this, "ERROR de base de datos"+ e.getMessage());
           e.printStackTrace();

        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "ERROR al agregar medicamento"+ e.getMessage());
           e.printStackTrace();
        }finally{
            try{
                if(rsReceta != null) rsReceta.close();
                if(pstReceta != null) pstReceta.close();
                if(pstDetalle != null) pstDetalle.close();
                if(cn != null) cn.close();
            }catch(SQLException e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed
*/
    //para que se guarde en la base de datos 
    
    
    private void comboMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMedicamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewAtencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewAtencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewAtencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewAtencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewAtencion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancel;
    private javax.swing.JButton BtnRegister;
    private javax.swing.JTextField TxtDiagnostico;
    private javax.swing.JTextField TxtObservacion;
    private javax.swing.JTextField TxtProcedimiento;
    private javax.swing.JTextField TxtipoExamen;
    private javax.swing.JComboBox<String> comboCita;
    private javax.swing.JComboBox<String> comboMedicamento;
    private javax.swing.JSpinner diasTratamiento;
    private javax.swing.JSpinner horasTratamiento;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelAmbiente;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelDni;
    private javax.swing.JLabel labelFechaCita;
    private javax.swing.JLabel labelHoraCita;
    private javax.swing.JLabel labelMedico;
    private javax.swing.JLabel labelMotivoCita;
    private javax.swing.JTable tablaReceta;
    private javax.swing.JSpinner vecesDiasTratamiento;
    // End of variables declaration//GEN-END:variables

    private void cargarCitas() {
      try{
          Connection cn = Conexion.getConnect().getConexion(); 
          String sql = "SELECT idCita, motivo FROM CITA"; 
          PreparedStatement ps = cn.prepareStatement(sql); 
          ResultSet rs = ps.executeQuery(); 
          
          comboCita.removeAllItems();
          while(rs.next()){
              comboCita.addItem(rs.getString("idCita")+ "-" + rs.getString("motivo"));
          }
          rs.close();
          ps.close();
          cn.close();
      } catch (Exception e){
          JOptionPane.showMessageDialog(this, "ERROR al cargar citas: " + e.getMessage());
      }
    }

    private void configurarTablaReceta() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
}
