/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Datos.DAmbiente;
import Datos.DCita;
import Datos.DEmpleado;
import Datos.DPaciente;
import Entidades.EAmbiente;
import Entidades.ECita;
import Entidades.EPaciente;
import Utils.GeneradorCode;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ENZO
 */
public class NewCita extends javax.swing.JFrame {
    
    private String codeGen;
    DAmbiente amb = new DAmbiente();
    DEmpleado pers = new DEmpleado();
    
    public NewCita() throws SQLException{
        initComponents();
        //CARGAMOS NUESTRO COMBOBOXMEDICO CON INFO DE LA BD
        pers.consultar_medicos(ComboBoxMedico);
        amb.consultar_consultorios(ComboBoxConsultorio);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        codeGen = GeneradorCode.CodeGenerador("CIT", null);
        this.codigoCita.setText(codeGen);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TxtDNI = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtMotivoCita = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CheckBoxEstado = new javax.swing.JCheckBox();
        BtnRegister = new javax.swing.JButton();
        BtnCancel = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        codigoCita = new javax.swing.JLabel();
        ComboBoxMedico = new javax.swing.JComboBox<>();
        ComboBoxConsultorio = new javax.swing.JComboBox<>();
        TxtFechaCita = new javax.swing.JTextField();
        TxtHoraCita = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingrese el DNI del paciente:");

        jLabel2.setText("Seleccione el Medico:");

        jLabel3.setText("Seleccione el consultorio:");

        jLabel4.setText("Ingrese la fecha de la cita: ");

        jLabel5.setText("Ingrese la hora de la cita: ");

        jLabel6.setText("Ingrese el motivo de la cita:");

        jLabel7.setText("Estado:");

        CheckBoxEstado.setSelected(true);
        CheckBoxEstado.setText("Activo");
        CheckBoxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxEstadoActionPerformed(evt);
            }
        });

        BtnRegister.setText("Registrar");
        BtnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegisterActionPerformed(evt);
            }
        });

        BtnCancel.setText("Cancelar");
        BtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelActionPerformed(evt);
            }
        });

        jLabel8.setText("Codigo de la cita:");

        codigoCita.setText("codigo");

        ComboBoxMedico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ComboBoxConsultorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BtnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TxtMotivoCita, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                        .addComponent(CheckBoxEstado)
                        .addComponent(BtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(codigoCita)
                        .addComponent(ComboBoxMedico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ComboBoxConsultorio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TxtFechaCita, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtHoraCita, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(codigoCita))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ComboBoxMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ComboBoxConsultorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtFechaCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxtHoraCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TxtMotivoCita, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CheckBoxEstado))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_BtnCancelActionPerformed

    private void CheckBoxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxEstadoActionPerformed

    private void BtnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegisterActionPerformed
        
        DPaciente pac = new DPaciente();
        DEmpleado emp = new DEmpleado();
        DAmbiente amb = new DAmbiente();
        
        //VALIDACIONES DE LOS DATOS NECESARIOS PARA EL REGISTRO DE LA CITA
        if(this.TxtDNI.getText().length() == 0){
           JOptionPane.showMessageDialog(rootPane, "Ingrese el Dni del paciente a saca cita");
           return; 
        }
        
        if( this.ComboBoxMedico.getSelectedIndex() <= 0){
            JOptionPane.showMessageDialog(rootPane, "Seleccione al Medico");
            return;
        } 
        
        if( this.ComboBoxConsultorio.getSelectedIndex() <= 0){
            JOptionPane.showMessageDialog(rootPane, "Seleccione el Consultorio");
            return;
        } 
        
        if(this.TxtFechaCita.getText().length() == 0){
           JOptionPane.showMessageDialog(rootPane, "Ingrese la fecha de la cita");
           return; 
        }
        
        if(this.TxtHoraCita.getText().length() == 0){
           JOptionPane.showMessageDialog(rootPane, "Ingrese la hora de la cita");
           return; 
        }
        
        if(this.TxtMotivoCita.getText().length() == 0){
           JOptionPane.showMessageDialog(rootPane, "Ingrese el motivo de la cita");
           return; 
        }
        
        if (!this.CheckBoxEstado.isSelected()) {
        JOptionPane.showMessageDialog(rootPane, "La Cita debe estar activa al registrarse");
        return;
        }
        
        ECita cit = new ECita();
        
        //FECHA DE LA CITA
        String fechaTexto = this.TxtFechaCita.getText();
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Date fechaCita = formato.parse(fechaTexto);
            cit.setFecha(fechaCita);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(rootPane, "Fecha mal ingresada en la fecha de la Cita, el formato es: Año-Mes-dia");
            return;
        }
        
        //HORA DE LA CITA
        String horaTexto = this.TxtHoraCita.getText(); // Ejemplo: "15:30"
        SimpleDateFormat formatoHora = new SimpleDateFormat("HH:mm");

        try {
            Date hora = formatoHora.parse(horaTexto);
            cit.setHora(hora); 
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(rootPane, "Hora de la Cita mal ingresada, el formato es: Hora:Minutos");
            return;
        }
        
        cit.setIdCita(codeGen);
        try {
            EPaciente paci = new EPaciente();
            paci.setIdPersona(pac.buscarIdPorDni(this.TxtDNI.getText()));
            cit.setPaciente(paci);
        } catch (SQLException ex) {
            Logger.getLogger(NewCita.class.getName()).log(Level.SEVERE, null, ex);
        }
        //SELECCIONAR UN MEDICO
        String apellidoPaterno;
        String apellidoMaterno;
        // Obtener el texto seleccionado del ComboBox
        String seleccion = this.ComboBoxMedico.getSelectedItem().toString().trim();

        // Dividir la cadena en partes usando espacios (considerando nombres compuestos)
        String[] partes = seleccion.split("\\s+", 3); // Máximo 3 partes: [paterno, materno, nombre]

        // Asignar las partes a las variables
        if (partes.length >= 1) {
            apellidoPaterno = partes[0];  // Primera parte: apellido paterno
        } else {
            apellidoPaterno = "";
        }

        if (partes.length >= 2) {
            apellidoMaterno = partes[1];  // Segunda parte: apellido materno
        } else {
            apellidoMaterno = "";
        }
        try {
            cit.setEmpleado(emp.buscarIdPorApellido(apellidoPaterno, apellidoMaterno));
        } catch (SQLException ex) {
            Logger.getLogger(NewCita.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            //SELECCIONAR UN CONSULTORIO EN EL COMBOBOX AMBIENTE
            EAmbiente ambi = new EAmbiente();
            ambi.setIdAmbiente((amb.buscarIdPorNombre(this.ComboBoxConsultorio.getSelectedItem().toString())));
            cit.setAmbiente(ambi);
        } catch (SQLException ex) {
            Logger.getLogger(NewCita.class.getName()).log(Level.SEVERE, null, ex);
        }
        cit.setMotivo(this.TxtMotivoCita.getText());
        
        int opcion = JOptionPane.showConfirmDialog(
            rootPane,
            "<html><b>Datos del Paciente:</b><br>" +
            "Dni Paciente: " + cit.getPaciente().getIdPersona() + "<br>" +
            "Medico: " + cit.getEmpleado().getIdPersona() + "<br>" +
            "Consultorio: " + cit.getAmbiente().getIdAmbiente() + "<br>" +
            "Fecha de la Cita: " + cit.getFecha() + "<br>" +
            "Hora de la Cita: " + cit.getHora() + "<br>" +
            "Motivo: " + cit.getMotivo() + "<br>",
            "Verificación del Registro",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.INFORMATION_MESSAGE
        );
        
        if (opcion != 0) {
            return;
        }
        
        DCita citDao = new DCita();
        
        try {
            citDao.registrarCita(cit);
            JOptionPane.showMessageDialog(rootPane, "Cita registrado correctamente ");
        }catch (SQLException ex) {
            Logger.getLogger(NewPaciente.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "La Cita no se pudo registrar, revise que los datos sean correctos.");
            return;
        }
        try {
            limpiar();
        }catch (SQLException ex) {
            Logger.getLogger(NewPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnRegisterActionPerformed
    public void limpiar() throws SQLException{
        this.TxtDNI.setText(null);
        this.ComboBoxMedico.setSelectedItem(1);
        this.ComboBoxConsultorio.setSelectedItem(1);
        this.TxtFechaCita.setText(null);
        this.TxtHoraCita.setText(null);
        this.TxtMotivoCita.setText(null);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new NewCita().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(NewCita.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancel;
    private javax.swing.JButton BtnRegister;
    private javax.swing.JCheckBox CheckBoxEstado;
    private javax.swing.JComboBox<String> ComboBoxConsultorio;
    private javax.swing.JComboBox<String> ComboBoxMedico;
    private javax.swing.JTextField TxtDNI;
    private javax.swing.JTextField TxtFechaCita;
    private javax.swing.JTextField TxtHoraCita;
    private javax.swing.JTextField TxtMotivoCita;
    private javax.swing.JLabel codigoCita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
