/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Datos.DEmpleado;
import Datos.DEspecialidad;
import Entidades.E_Empleado;
import Entidades.E_Especialidad;
import Entidades.Rol;
import Utils.GeneradorCode;
import java.awt.event.ActionEvent;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ESTUDIANTE
 */
public class NewEmpleado extends javax.swing.JFrame {
    
    private String rolTemp;
    private String codeGenerado;
    private E_Empleado emp = new E_Empleado();

    public NewEmpleado() {
        initComponents();        
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        rolTemp = "Seleccionar";
        this.ComboxRolEmp.addActionListener((ActionEvent e) -> {
            String rolSeleccionado = (String) ComboxRolEmp.getSelectedItem();
            if(rolSeleccionado == null || rolSeleccionado.equals(rolTemp)){ return; }
            rolTemp = rolSeleccionado;
            if(rolTemp.equals("Seleccionar")){ 
                this.TxtCode.setText("Seleccione un rol para generar el codigo.");
                codeGenerado = null;
                return; 
            }
            
            if(!rolSeleccionado.equals("Medico")){
                this.ComboxEspecialidadEmp.setSelectedIndex(ComboxEspecialidadEmp.getItemCount() - 1);
                this.ComboxEspecialidadEmp.setEnabled(false);
            }else{
                this.ComboxEspecialidadEmp.setSelectedIndex(0);
                this.ComboxEspecialidadEmp.setEnabled(true);
            }
            
            try {
                colocarCodigo(rolSeleccionado.toUpperCase());
            } catch (SQLException ex) {
                Logger.getLogger(NewEmpleado.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
        cargarRoles();
        cargarEspecialidades();
    }
    
    public NewEmpleado(E_Empleado emp) {
        initComponents();        
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        rolTemp = "Seleccionar";
        this.ComboxRolEmp.addActionListener((ActionEvent e) -> {
            String rolSeleccionado = (String) ComboxRolEmp.getSelectedItem();
            if(rolSeleccionado == null || rolSeleccionado.equals(rolTemp)){ return; }
            rolTemp = rolSeleccionado;
            if(rolTemp.equals("Seleccionar")){ 
                this.TxtCode.setText("Seleccione un rol para generar el codigo.");
                codeGenerado = null;
                return; 
            }
            
            if(!rolSeleccionado.equals("Medico")){
                this.ComboxEspecialidadEmp.setSelectedIndex(ComboxEspecialidadEmp.getItemCount() - 1);
                this.ComboxEspecialidadEmp.setEnabled(false);
            }else{
                this.ComboxEspecialidadEmp.setSelectedIndex(0);
                this.ComboxEspecialidadEmp.setEnabled(true);
            }
            
            try {
                colocarCodigo(rolSeleccionado.toUpperCase());
            } catch (SQLException ex) {
                Logger.getLogger(NewEmpleado.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
        cargarRoles();
        cargarEspecialidades();
    }
    
    private void colocarCodigo(String rol) throws SQLException{
        codeGenerado = GeneradorCode.CodeGenerador("EMP", rol);
        this.TxtCode.setText(codeGenerado);
    }
    
    private void cargarEspecialidades(){
        this.ComboxEspecialidadEmp.removeAllItems();
        this.ComboxEspecialidadEmp.addItem("Seleccionar");
        List<E_Especialidad> listaEsp = DEspecialidad.listarEspecialidades();
        for( E_Especialidad obj : listaEsp ){
            this.ComboxEspecialidadEmp.addItem(obj.getNombre());
        }
        this.ComboxEspecialidadEmp.addItem("No Tiene");
    }
    
    private void cargarRoles() {
        this.ComboxRolEmp.removeAllItems();
        this.ComboxRolEmp.addItem("Seleccionar");
        // Recorrer el enum Rol para añadir las opciones
        for (Rol rol : Rol.values()) {
            if (rol.getDbValue().equalsIgnoreCase("Medico") || rol.getDbValue().equalsIgnoreCase("Enfermero") || rol.getDbValue().equalsIgnoreCase("Seguridad") || rol.getDbValue().equalsIgnoreCase("Limpieza")) { 
                this.ComboxRolEmp.addItem(rol.getDbValue());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtDni = new javax.swing.JTextField();
        TxtEmail = new javax.swing.JTextField();
        TxtApellidoPa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        CbActivo = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        TxtEmail1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BtnCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        TxtApellidoMa = new javax.swing.JTextField();
        ComboxRolEmp = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        TxtNombres = new javax.swing.JTextField();
        BtnRegistrar = new javax.swing.JButton();
        TxtTelefono = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CbDisponible = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        ComboxEspecialidadEmp = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        TxtCode = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        BtnRegistroHorarios = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        TxtGenero = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(TxtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 220, -1));
        getContentPane().add(TxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 218, -1));
        getContentPane().add(TxtApellidoPa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 218, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(68, 1, 30));
        jLabel4.setText("Fecha Nacimiento:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(68, 1, 30));
        jLabel11.setText("Dirección Domicilio:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        CbActivo.setForeground(new java.awt.Color(102, 102, 102));
        CbActivo.setSelected(true);
        CbActivo.setText("Activo");
        CbActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbActivoActionPerformed(evt);
            }
        });
        getContentPane().add(CbActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 620, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(68, 1, 30));
        jLabel2.setText("Nombres:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));
        getContentPane().add(TxtEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 220, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(68, 1, 30));
        jLabel6.setText("Telefono:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        BtnCancelar.setBackground(new java.awt.Color(68, 1, 30));
        BtnCancelar.setFont(new java.awt.Font("Agave Nerd Font", 1, 20)); // NOI18N
        BtnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancelar.setText("CANCELAR");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 690, 140, 47));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(68, 1, 30));
        jLabel5.setText("Rol:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, -1, -1));
        getContentPane().add(TxtApellidoMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 218, -1));

        ComboxRolEmp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboxRolEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboxRolEmpActionPerformed(evt);
            }
        });
        getContentPane().add(ComboxRolEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 220, -1));

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(68, 1, 30));
        jLabel9.setText("Apellido Materno:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));
        getContentPane().add(TxtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 218, -1));

        BtnRegistrar.setBackground(new java.awt.Color(68, 1, 30));
        BtnRegistrar.setFont(new java.awt.Font("Agave Nerd Font", 1, 20)); // NOI18N
        BtnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegistrar.setText("REGISTRAR");
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 690, 150, 47));
        getContentPane().add(TxtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 220, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(68, 1, 30));
        jLabel3.setText("Dni:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(68, 1, 30));
        jLabel8.setText("Email:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(68, 1, 30));
        jLabel1.setText("Codigo Empleado:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(68, 1, 30));
        jLabel12.setText("Estado:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 620, -1, 20));

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(68, 1, 30));
        jLabel13.setText("Disponibilidad:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 590, -1, -1));

        CbDisponible.setForeground(new java.awt.Color(102, 102, 102));
        CbDisponible.setSelected(true);
        CbDisponible.setText("Disponible");
        CbDisponible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbDisponibleActionPerformed(evt);
            }
        });
        getContentPane().add(CbDisponible, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 590, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(68, 1, 30));
        jLabel7.setText("Especialidad:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, -1, -1));

        ComboxEspecialidadEmp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboxEspecialidadEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboxEspecialidadEmpActionPerformed(evt);
            }
        });
        getContentPane().add(ComboxEspecialidadEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 218, -1));

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(68, 1, 30));
        jLabel10.setText("Apellido Paterno:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        TxtCode.setForeground(new java.awt.Color(102, 102, 102));
        TxtCode.setText("Seleccione un rol para generar el codigo.");
        getContentPane().add(TxtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 210, -1));

        BtnRegistroHorarios.setText("Registrar Horarios");
        BtnRegistroHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistroHorariosActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRegistroHorarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 600, -1, -1));

        jLabel14.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 0, 51));
        jLabel14.setText("Genero:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, -1, -1));
        getContentPane().add(TxtGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, 220, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Registro de empleado.png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CbActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbActivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbActivoActionPerformed

    private void ComboxRolEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboxRolEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboxRolEmpActionPerformed

    private void CbDisponibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbDisponibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbDisponibleActionPerformed

    private void ComboxEspecialidadEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboxEspecialidadEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboxEspecialidadEmpActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnRegistroHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistroHorariosActionPerformed
        NewHorario nh = new NewHorario(emp.getHorarios());
        nh.setVisible(true);
    }//GEN-LAST:event_BtnRegistroHorariosActionPerformed

    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed
        try {
            // Validar campos obligatorios
            if (!validarCampos()) {
                return;
            }

            // Construir el objeto empleado usando el patrón Builder
            E_Empleado nuevoEmpleado = construirEmpleado();

            DEmpleado empDao = new DEmpleado();
            empDao.registrarEmpleadoCompleto(nuevoEmpleado);

            javax.swing.JOptionPane.showMessageDialog(this, 
                "Empleado registrado exitosamente!\nCódigo: " + nuevoEmpleado.getIdPersona(), 
                "Registro Exitoso", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // Limpiar formulario después del registro exitoso
            limpiarFormulario();

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Error al registrar empleado: " + ex.getMessage(), 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(NewEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnRegistrarActionPerformed

    private E_Empleado construirEmpleado() {
        // Obtener datos del formulario
        String nombres = TxtNombres.getText().trim();
        String apellidoPaterno = TxtApellidoPa.getText().trim();
        String apellidoMaterno = TxtApellidoMa.getText().trim();
        String dni = TxtDni.getText().trim();
        String telefono = TxtTelefono.getText().trim();
        String email = TxtEmail1.getText().trim();
        String direccion = TxtEmail.getText().trim();
        String genero = this.TxtGenero.getText().trim();

        // Obtener rol seleccionado
        String rolSeleccionado = (String) ComboxRolEmp.getSelectedItem();
        Rol rol = obtenerRolPorNombre(rolSeleccionado);

        // Obtener especialidad (solo si es médico)
        E_Especialidad especialidad = null;
        if (rolSeleccionado.equals("Medico")) {
            String especialidadNombre = (String) ComboxEspecialidadEmp.getSelectedItem();
            if (!especialidadNombre.equals("Seleccionar") && !especialidadNombre.equals("No Tiene")) {
                especialidad = obtenerEspecialidadPorNombre(especialidadNombre);
            }
        }

        // Obtener fecha de nacimiento
        java.util.Date fechaNacimiento = jDateChooser1.getDate();

        // Obtener estados de los checkboxes
        boolean disponible = CbDisponible.isSelected();
        boolean activo = CbActivo.isSelected();

        // Fecha de ingreso (fecha actual)
        java.util.Date fechaIngreso = new java.util.Date();

        // Construir el empleado usando el patrón Builder
        E_Empleado empleado = E_Empleado.builder()
            .setIdPersona(codeGenerado)
            .setNombre(nombres)
            .setApellidoPaterno(apellidoPaterno)
            .setApellidoMaterno(apellidoMaterno)
            .setDni(dni)
            .setTelefono(telefono)
            .setCorreo(email)
            .setDireccion(direccion)
            .setFechaNacimiento(fechaNacimiento)
            .setRol(rol)
            .setDisponibilidad(disponible)
            .setEstado(activo)
            .setFechaIngreso(fechaIngreso)
            .setEspecialidad(especialidad)
            .setHorarios(emp.getHorarios())
            .setGenero(genero)
            .build();

        return empleado;
    }
    
    private boolean validarCampos() {
        StringBuilder errores = new StringBuilder();

        // Validar código generado
        if (codeGenerado == null || codeGenerado.isEmpty()) {
            errores.append("- Debe seleccionar un rol para generar el código\n");
        }

        // Validar campos de texto obligatorios
        if (TxtNombres.getText().trim().isEmpty()) {
            errores.append("- El nombre es obligatorio\n");
        }

        if (TxtApellidoPa.getText().trim().isEmpty()) {
            errores.append("- El apellido paterno es obligatorio\n");
        }

        if (TxtApellidoMa.getText().trim().isEmpty()) {
            errores.append("- El apellido materno es obligatorio\n");
        }

        if (TxtDni.getText().trim().isEmpty()) {
            errores.append("- El DNI es obligatorio\n");
        } else if (!validarDNI(TxtDni.getText().trim())) {
            errores.append("- El DNI debe tener 8 dígitos\n");
        }

        if (TxtTelefono.getText().trim().isEmpty()) {
            errores.append("- El teléfono es obligatorio\n");
        }

        if (TxtEmail1.getText().trim().isEmpty()) {
            errores.append("- El email es obligatorio\n");
        } else if (!validarEmail(TxtEmail1.getText().trim())) {
            errores.append("- El formato del email no es válido\n");
        }

        if (TxtEmail.getText().trim().isEmpty()) {
            errores.append("- La dirección es obligatoria\n");
        }

        // Validar fecha de nacimiento
        if (jDateChooser1.getDate() == null) {
            errores.append("- La fecha de nacimiento es obligatoria\n");
        }

        // Validar rol
        String rolSeleccionado = (String) ComboxRolEmp.getSelectedItem();
        if (rolSeleccionado == null || rolSeleccionado.equals("Seleccionar")) {
            errores.append("- Debe seleccionar un rol\n");
        }

        // Validar especialidad para médicos
        if ("Medico".equals(rolSeleccionado)) {
            String especialidadSeleccionada = (String) ComboxEspecialidadEmp.getSelectedItem();
            if (especialidadSeleccionada == null || especialidadSeleccionada.equals("Seleccionar")) {
                errores.append("- Debe seleccionar una especialidad para el médico\n");
            }
        }

        // Mostrar errores si existen
        if (errores.length() > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Por favor corrija los siguientes errores:\n\n" + errores.toString(), 
                "Errores de validación", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return false;
        }

        return true;
    }

    private boolean validarDNI(String dni) {
        return dni.matches("\\d{8}");
    }

    private boolean validarEmail(String email) {
        return email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$");
    }

    private Rol obtenerRolPorNombre(String nombreRol) {
        for (Rol rol : Rol.values()) {
            if (rol.getDbValue().equalsIgnoreCase(nombreRol)) {
                return rol;
            }
        }
        return null; // o lanzar una excepción
    }

    private E_Especialidad obtenerEspecialidadPorNombre(String nombreEspecialidad) {
        // Aquí deberías buscar la especialidad en tu base de datos o lista
        // Por ejemplo, usando tu clase DEspecialidad:
        List<E_Especialidad> especialidades = DEspecialidad.listarEspecialidades();
        for (E_Especialidad esp : especialidades) {
            if (esp.getNombre().equals(nombreEspecialidad)) {
                return esp;
            }
        }
        return null;
    }

    private void limpiarFormulario() {
        TxtNombres.setText("");
        TxtApellidoPa.setText("");
        TxtApellidoMa.setText("");
        TxtDni.setText("");
        TxtTelefono.setText("");
        TxtEmail1.setText("");
        TxtEmail.setText("");
        jDateChooser1.setDate(null);

        ComboxRolEmp.setSelectedIndex(0);
        ComboxEspecialidadEmp.setSelectedIndex(0);

        CbDisponible.setSelected(true);
        CbActivo.setSelected(true);

        TxtCode.setText("Seleccione un rol para generar el codigo.");
        codeGenerado = null;
        rolTemp = "Seleccionar";

        // Limpiar horarios del empleado temporal
        emp.getHorarios().clear();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JButton BtnRegistroHorarios;
    private javax.swing.JCheckBox CbActivo;
    private javax.swing.JCheckBox CbDisponible;
    private javax.swing.JComboBox<String> ComboxEspecialidadEmp;
    private javax.swing.JComboBox<String> ComboxRolEmp;
    private javax.swing.JTextField TxtApellidoMa;
    private javax.swing.JTextField TxtApellidoPa;
    private javax.swing.JLabel TxtCode;
    private javax.swing.JTextField TxtDni;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtEmail1;
    private javax.swing.JTextField TxtGenero;
    private javax.swing.JTextField TxtNombres;
    private javax.swing.JTextField TxtTelefono;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
