/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Entidades.DiaSemana;
import Entidades.EHorario;
import Utils.GeneradorCode;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ENZO
 */
public class NewHorario extends javax.swing.JFrame {

    public DefaultTableModel modelo;
    String cabecera[] = {"Dia", "Hora de Entrada", "Hora de Salida"};
    List<EHorario> listaHorarios = new ArrayList<>();

    public NewHorario(List<EHorario> horarios) {
        listaHorarios = horarios;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        modelo = new DefaultTableModel ( null, cabecera );
        this.TableHorarios.setModel(modelo);
        cargarDias();
        actualizarTabla(listaHorarios);
        ordenarTablaPorDia();
    }
    
    private void cargarDias() {
        this.ComboxDia.removeAllItems();
        this.ComboxDia.addItem("Seleccionar");
        // Recorrer el enum Rol para añadir las opciones
        for (DiaSemana dia : DiaSemana.values()) {
            this.ComboxDia.addItem(dia.getDbValue());
        }
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BtnRegister = new javax.swing.JButton();
        BtnCancel = new javax.swing.JButton();
        ComboxDia = new javax.swing.JComboBox<>();
        entradaTime = new lu.tudor.santec.jtimechooser.JTimeChooser();
        salidaTime = new lu.tudor.santec.jtimechooser.JTimeChooser();
        BtnAgregarHorario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableHorarios = new javax.swing.JTable();
        labelbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(68, 1, 30));
        jLabel3.setText("Ingrese el dia del turno:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(68, 1, 30));
        jLabel4.setText("Ingrese la hora de entrada:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(68, 1, 30));
        jLabel5.setText("Ingrese la hora de salida:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        BtnRegister.setBackground(new java.awt.Color(68, 1, 30));
        BtnRegister.setFont(new java.awt.Font("Agave Nerd Font", 1, 22)); // NOI18N
        BtnRegister.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegister.setText("Aceptar");
        BtnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 140, 40));

        BtnCancel.setBackground(new java.awt.Color(68, 1, 30));
        BtnCancel.setFont(new java.awt.Font("Agave Nerd Font", 1, 22)); // NOI18N
        BtnCancel.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancel.setText("Cancelar");
        BtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, 130, 40));

        ComboxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(ComboxDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 150, -1));

        entradaTime.setShowSeconds(false);
        getContentPane().add(entradaTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 150, -1));

        salidaTime.setShowSeconds(false);
        getContentPane().add(salidaTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 150, -1));

        BtnAgregarHorario.setText("Agregar / Modificar");
        BtnAgregarHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarHorarioActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAgregarHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        TableHorarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableHorarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 380, 220));

        labelbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Horarioo.png"))); // NOI18N
        labelbackground.setToolTipText("");
        labelbackground.setAutoscrolls(true);
        getContentPane().add(labelbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 550));
        try {
            javax.swing.ImageIcon originalIcon = new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Horarioo.png"));

            labelbackground.addComponentListener(new java.awt.event.ComponentAdapter() {
                @Override
                public void componentResized(java.awt.event.ComponentEvent evt) {
                    int labelWidth = labelbackground.getWidth();
                    int labelHeight = labelbackground.getHeight();

                    if (labelWidth > 0 && labelHeight > 0) {
                        // Crear imagen con alta calidad
                        java.awt.image.BufferedImage scaledImage = new java.awt.image.BufferedImage(
                            labelWidth, labelHeight, java.awt.image.BufferedImage.TYPE_INT_ARGB);

                        java.awt.Graphics2D g2 = scaledImage.createGraphics();
                        g2.setRenderingHint(java.awt.RenderingHints.KEY_INTERPOLATION,
                            java.awt.RenderingHints.VALUE_INTERPOLATION_BILINEAR);
                        g2.setRenderingHint(java.awt.RenderingHints.KEY_RENDERING,
                            java.awt.RenderingHints.VALUE_RENDER_QUALITY);
                        g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING,
                            java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                        g2.drawImage(originalIcon.getImage(), 0, 0, labelWidth, labelHeight, null);
                        g2.dispose();

                        labelbackground.setIcon(new javax.swing.ImageIcon(scaledImage));
                    }
                }
            });

            // Trigger inicial
            javax.swing.SwingUtilities.invokeLater(() -> {
                if (labelbackground.getComponentListeners().length > 0) {
                    labelbackground.getComponentListeners()[labelbackground.getComponentListeners().length-1]
                    .componentResized(new java.awt.event.ComponentEvent(labelbackground, java.awt.event.ComponentEvent.COMPONENT_RESIZED));
                }
            });

        } catch (Exception e) {
            System.err.println("Error cargando imagen: " + e.getMessage());
        }

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegisterActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnRegisterActionPerformed

    private void BtnAgregarHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarHorarioActionPerformed
        EHorario horario = null;
        try {
            // Validaciones de campos vacíos o nulos
            if (this.ComboxDia.getSelectedItem() == null || 
                this.ComboxDia.getSelectedItem().toString().trim().isEmpty() ||
                this.ComboxDia.getSelectedIndex() == 0) { // Asumiendo que index 0 es "Seleccionar"
                JOptionPane.showMessageDialog(this, 
                    "Por favor seleccione un día de la semana.", 
                    "Campo requerido", 
                    JOptionPane.WARNING_MESSAGE);
                this.ComboxDia.requestFocus();
                return;
            }

            // Validación correcta para JTimeChooser
            if (this.entradaTime.getTimeField().getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, 
                    "Por favor ingrese la hora de entrada.", 
                    "Campo requerido", 
                    JOptionPane.WARNING_MESSAGE);
                this.entradaTime.requestFocus();
                return;
            }

            if (this.salidaTime.getTimeField().getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, 
                    "Por favor ingrese la hora de salida.", 
                    "Campo requerido", 
                    JOptionPane.WARNING_MESSAGE);
                this.salidaTime.requestFocus();
                return;
            }

            // Obtener valores de los campos
            String diaSeleccionado = (String) this.ComboxDia.getSelectedItem();
            String horaEntradaStr = this.entradaTime.getFormatedTime();
            String horaSalidaStr = this.salidaTime.getFormatedTime();

            // Validación adicional de formato
            if (horaEntradaStr == null || horaEntradaStr.trim().isEmpty() || horaEntradaStr.equals("00:00")) {
                JOptionPane.showMessageDialog(this, 
                    "Por favor ingrese una hora de entrada válida.", 
                    "Campo requerido", 
                    JOptionPane.WARNING_MESSAGE);
                this.entradaTime.requestFocus();
                return;
            }

            if (horaSalidaStr == null || horaSalidaStr.trim().isEmpty() || horaSalidaStr.equals("00:00")) {
                JOptionPane.showMessageDialog(this, 
                    "Por favor ingrese una hora de salida válida.", 
                    "Campo requerido", 
                    JOptionPane.WARNING_MESSAGE);
                this.salidaTime.requestFocus();
                return;
            }

            // Convertir strings de tiempo a LocalTime para comparación
            LocalTime horaEntrada = LocalTime.parse(horaEntradaStr, DateTimeFormatter.ofPattern("HH:mm"));
            LocalTime horaSalida = LocalTime.parse(horaSalidaStr, DateTimeFormatter.ofPattern("HH:mm"));

            // Validación: verificar si ya existe un horario para ese día
            DiaSemana diaEnum = DiaSemana.fromDbValue(diaSeleccionado);
            boolean diaYaExiste = listaHorarios.stream()
                    .anyMatch((EHorario horario1) -> horario1.getDia().equals(diaEnum));

            if (diaYaExiste) {
                int respuesta = JOptionPane.showConfirmDialog(this, 
                    "Ya existe un horario para " + diaSeleccionado + ". ¿Desea reemplazarlo?", 
                    "Día duplicado", 
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

                if (respuesta == JOptionPane.NO_OPTION) {
                    return;
                } else {
                    // Eliminar el horario existente para ese día
                    listaHorarios.removeIf((EHorario horario1) -> horario1.getDia().equals(diaEnum));
                    // También eliminar de la tabla
                    for (int i = 0; i < this.modelo.getRowCount(); i++) {
                        if (this.modelo.getValueAt(i, 0).equals(diaSeleccionado)) {
                            this.modelo.removeRow(i);
                            break;
                        }
                    }
                }
            }

            // Crear nuevo objeto EHorario
            horario = new EHorario(
                null,
                diaEnum,
                horaEntrada,
                horaSalida
            );

            // Agregar a la lista PRIMERO (para mantener consistencia)
            listaHorarios.add(horario);

            // Agregar fila a la tabla
            String fila[] = {
                diaSeleccionado,
                horaEntradaStr,
                horaSalidaStr
            };
            this.modelo.addRow(fila);

            // Opcional: ordenar la tabla por día de la semana
            ordenarTablaPorDia();

            // Limpiar campos después de agregar exitosamente
            this.ComboxDia.setSelectedIndex(0);

            // Mensaje de confirmación
            JOptionPane.showMessageDialog(this, 
                "Horario agregado correctamente.", 
                "Éxito", 
                JOptionPane.INFORMATION_MESSAGE);

        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, 
                "Error en el formato de hora. Por favor verifique que las horas estén en formato HH:mm", 
                "Error de formato", 
                JOptionPane.ERROR_MESSAGE);
            // Si hay error de parsing, no agregamos nada
            return;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error al agregar el horario: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            // Si el horario se creó pero hubo error después, lo removemos de la lista
            if (horario != null && listaHorarios.contains(horario)) {
                listaHorarios.remove(horario);
            }
            return;
        }
    }//GEN-LAST:event_BtnAgregarHorarioActionPerformed

    private void BtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnCancelActionPerformed

    private void actualizarTabla( List<EHorario> listaHorarios ){
        if (listaHorarios != null ||  !listaHorarios.isEmpty()) {
            for( EHorario obj : listaHorarios ){
                // Agregar fila a la tabla
                String fila[] = {
                    obj.getDia().getDbValue(),
                    obj.getHoraEntrada().toString(),
                    obj.getHoraSalida().toString()
                };
                this.modelo.addRow(fila);
            }
        }
    }
    
   private void ordenarTablaPorDia() {
    try {
        // Crear un array con el orden deseado de los días
        String[] ordenDias = {"Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo"};

        // Obtener datos actuales de la tabla
        java.util.List<String[]> filas = new java.util.ArrayList<>();
        for (int i = 0; i < this.modelo.getRowCount(); i++) {
            String[] fila = new String[3];
            fila[0] = (String) this.modelo.getValueAt(i, 0); // Día
            fila[1] = (String) this.modelo.getValueAt(i, 1); // Entrada
            fila[2] = (String) this.modelo.getValueAt(i, 2); // Salida
            filas.add(fila);
        }

        // Ordenar según el orden de días establecido
        filas.sort((f1, f2) -> {
            int index1 = java.util.Arrays.asList(ordenDias).indexOf(f1[0]);
            int index2 = java.util.Arrays.asList(ordenDias).indexOf(f2[0]);
            return Integer.compare(index1, index2);
        });

        // Limpiar tabla y agregar filas ordenadas
        this.modelo.setRowCount(0);
        for (String[] fila : filas) {
            this.modelo.addRow(fila);
        }

        // También reordenar la lista de horarios para mantener consistencia
        listaHorarios.sort((h1, h2) -> {
            int index1 = java.util.Arrays.asList(ordenDias).indexOf(h1.getDia().getDbValue());
            int index2 = java.util.Arrays.asList(ordenDias).indexOf(h2.getDia().getDbValue());
            return Integer.compare(index1, index2);
        });

    } catch (Exception e) {
        // Si falla el ordenamiento, no es crítico, solo log
        System.err.println("Error al ordenar tabla: " + e.getMessage());
    }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewHorario(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregarHorario;
    private javax.swing.JButton BtnCancel;
    private javax.swing.JButton BtnRegister;
    private javax.swing.JComboBox<String> ComboxDia;
    private javax.swing.JTable TableHorarios;
    private lu.tudor.santec.jtimechooser.JTimeChooser entradaTime;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelbackground;
    private lu.tudor.santec.jtimechooser.JTimeChooser salidaTime;
    // End of variables declaration//GEN-END:variables
}
